spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: sql3681627
        url: jdbc:mysql://sql3.freesqldatabase.com:3306/sql3681627
        password: jYh8PUbzsq
    jpa:
        hibernate:
            ddl-auto: update
server:
    servlet:
        context-path: /online-shopping-store
